### ISSUE TITLE
Please publish latest code to npm

### ISSUE THREAD

**Issue by longbill** [LastLeaf/node-fastcgi-client#2]
Hi,

Thanks for your great work. I've created a project based on your work.  But I noticed that the code on npm is not the latest.  Please publish the latest code to npm, so that it supports the sockFile option.

Regards,
Chunlong

**Comment by longbill** [comment]
BTW, my project is  https://github.com/longbill/node-phpfpm

**Comment by LastLeaf** [comment]
Great job!

I have published it as version 0.0.1. Please check it.

You might like to take a look at my another repo [node-fpm](https://github.com/LastLeaf/node-fpm).
It works differently (by manage php workers directly, not through php-fpm), but not finished yet.

Currently I have little time to manage these repo, sorry.
Thanks for your contribution!
