### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by ashwinsingh2007** [LastLeaf/node-fastcgi-client#3]
Hi,
I have my php-fpm running on 127.0.0.1:9000 but when running "npm test" i am getting error-
"uncaught assertion error file not found-helloworld"
I have file helloworld file in www folder of node-fastcgi-client but still getting the error

**Comment by LastLeaf** [comment]
I have not seen this problem before. I guess it is related to PHP configurations and the FastCGI params used in the test script.

If you know some details about FastCGI params, you could take a look at [test/requests](https://github.com/LastLeaf/node-fastcgi-client/blob/master/test/requests.js) to see whether the params are right.

Currently, the params used in the test script are brought from nginx. Could you try serving the script with nginx?
