### ISSUE TITLE
how can I set cookie?

### ISSUE THREAD

**Issue by witwave** [LastLeaf/node-fastcgi-client#4]
I use the HTTP_COOKIE  params that i can get cookie in php, but i can't set cookie in php. so  how to support this function

**Comment by LastLeaf** [comment]
Sorry, I have already forgot the protocol details. I need some time to inspect.

Please be aware that I do not use this module in any project. I do not suggest you using in any productional environment.

**Comment by LastLeaf** [comment]
PHP response should contain a [Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) header. The header is in the `stdout`. Try parsing it in node?

**Comment by witwave** [comment]
Ok, you are right, I have done it
